---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-example-config
  namespace: capi-self
data:
  values.yaml: |
    # Must match the name of the (sealed) secret in credentials.yaml
    cloudCredentialsSecretName: cluster-dawntest-credentials

    # inject debug ssh key
    machineSSHKeyName: johng

    kubernetesVersion: 1.31.4
    machineImageId: "6ed3da4b-3b65-4d44-959f-f35956db1c78"

    clusterNetworking:
      externalNetworkId: "4d00778c-303f-49b2-b624-e3004262312d"
      internalNetwork:
        networkFilter:
          id: 5ee983c5-12b2-4bf4-83c6-e7cb394801e0
          name: bm-test-net

    controlPlane:
      machineFlavor: "vm.v1.small"
      machineCount: 3

    nodeGroups:
      - name: vm
        machineFlavor: "vm.v1.small"
        machineCount: 2
      - name: dawn
        machineFlavor: "bm.xe9640.xp8468.m1024.pvc.gpu"
        machineCount: 2

    addons:
      cni:
        type: cilium
        cilium:
          release:
            values:
              hubble:
                relay:
                  enabled: true
                ui:
                  enabled: true
      monitoring:
        enabled: true
      csi:
        cephfs:
          enabled: true
      openstack:
        enabled: true
        # turn off cinder, as it doesn't work with baremetal
        csiCinder:
          enabled: false
        csiManila:
          enabled: true
          defaultStorageClass:
            isClusterDefault: true
            parameters:
              type: ceph01_cephfs
      nodeFeatureDiscovery:
        enabled: true
      nvidiaGPUOperator:
        enabled: false
      mellanoxNetworkOperator:
        enabled: true
        release:
          values:
            # TODO work through
            # https://docs.nvidia.com/networking/display/kubernetes2410/getting+started+with+kubernetes#src-2494425587_GettingStartedwithKubernetes-NetworkOperatorDeploymentwithanSR-IOVInfiniBandNetworkwithPKeyManagement
            # turn off the shared plugin
            rdmaSharedDevicePlugin:
              deploy: false
            # we try to use SRIOV with host devs
            sriovDevicePlugin:
              deploy: true
            ibKubernetes:
              deploy: true
            secondaryNetwork:
              deploy: true
      ingress:
        enabled: true
        nginx:
          release:
            values:
              controller:
                extraArgs:
                  enable-ssl-passthrough: "true"
